using Godot;
using MegaCrit.Sts2.Core.Helpers;
using MegaCrit.Sts2.Core.Models;
using Yixian.Cards.HeptastarPavilion;

namespace Yixian.Characters;

/// <summary>Yixian Heptastar Pavilion Card Pool Model.</summary>
public sealed class YxHeptastarPavilionCardPool : CardPoolModel
{
    public override string Title => StringHelper.SnakeCase(nameof(YxHeptastarPavilion));
    public override string CardFrameMaterialPath => "card_frame_" + Title;
    public override string EnergyColorName => YxHeptastarPavilion.ENERGY_COLOR_NAME;
    public override Color EnergyOutlineColor => YxHeptastarPavilion.ENERGY_OUTLINE_COLOR;
    public override Color DeckEntryCardColor => YxHeptastarPavilion.DECK_ENTRY_CARD_COLOR;
    public override bool IsColorless => false;
    protected override CardModel[] GenerateAllCards() => [
        ModelDb.Card<YxAllOrNothing>(),
        ModelDb.Card<YxAstralFleche>(),
        ModelDb.Card<YxAstralMoveBlock>(),
        ModelDb.Card<YxAstralMoveCide>(),
        ModelDb.Card<YxAstralMoveDragonSlay>(),
        ModelDb.Card<YxAstralMoveFlank>(),
        ModelDb.Card<YxAstralMoveFly>(),
        ModelDb.Card<YxAstralMoveHit>(),
        ModelDb.Card<YxAstralMovePoint>(),
        ModelDb.Card<YxAstralMoveStand>(),
        ModelDb.Card<YxAstralMoveTiger>(),
        ModelDb.Card<YxAstralMoveTwinSwallows>(),
        ModelDb.Card<YxCovertShift>(),
        ModelDb.Card<YxCuttingWeeds>(),
        ModelDb.Card<YxDanceOfTheDragonfly>(),
        ModelDb.Card<YxDefendHeptastarPavilion>(),
        ModelDb.Card<YxDestinyCatastrophe>(),
        ModelDb.Card<YxDottedAround>(),
        ModelDb.Card<YxDragMoonInSea>(),
        ModelDb.Card<YxEarthHexagram>(),
        ModelDb.Card<YxEscapePlan>(),
        ModelDb.Card<YxFaceIsolation>(),
        ModelDb.Card<YxFallingThunder>(),
        ModelDb.Card<YxFiveThunders>(),
        ModelDb.Card<YxFlameFlutter>(),
        ModelDb.Card<YxFlameHexagram>(),
        ModelDb.Card<YxFlowersAndWater>(),
        ModelDb.Card<YxFlowerSentient>(),
        ModelDb.Card<YxFuryThunder>(),
        ModelDb.Card<YxGoldenRoosterIndependence>(),
        ModelDb.Card<YxGreatSpirit>(),
        ModelDb.Card<YxHeavenHexagram>(),
        ModelDb.Card<YxHeptastarSoulstat>(),
        ModelDb.Card<YxHexagramFormacide>(),
        ModelDb.Card<YxHexgramsSpiritResurrection>(),
        ModelDb.Card<YxHunterBecomesPreyer>(),
        ModelDb.Card<YxHunterHuntingHunter>(),
        ModelDb.Card<YxImposing>(),
        ModelDb.Card<YxIncessant>(),
        ModelDb.Card<YxJadeScrollOfYinSymbol>(),
        ModelDb.Card<YxLakeHexagram>(),
        ModelDb.Card<YxMeteoriteMeteor>(),
        ModelDb.Card<YxMountainHexagram>(),
        ModelDb.Card<YxOnlyTraces>(),
        ModelDb.Card<YxPalmThunder>(),
        ModelDb.Card<YxPerfectlyPlanned>(),
        ModelDb.Card<YxPolarisCittaDharma>(),
        ModelDb.Card<YxPreemptiveStrike>(),
        ModelDb.Card<YxPropitiousOmen>(),
        ModelDb.Card<YxPropitiousOmenEnergy>(),
        ModelDb.Card<YxPropitiousOmenHexagram>(),
        ModelDb.Card<YxPropitiousOmenStarPower>(),
        ModelDb.Card<YxQiTherapy>(),
        ModelDb.Card<YxRepelCittaDharma>(),
        ModelDb.Card<YxRevitalized>(),
        ModelDb.Card<YxRotaryDivinationHexagram>(),
        ModelDb.Card<YxRuthlessWater>(),
        ModelDb.Card<YxShiftingStars>(),
        ModelDb.Card<YxSnakeInReflection>(),
        ModelDb.Card<YxSolitaryVoidGoldenScroll>(),
        ModelDb.Card<YxSparrowsTail>(),
        ModelDb.Card<YxSpiritualDivination>(),
        ModelDb.Card<YxStarBornRhythm>(),
        ModelDb.Card<YxStarburst>(),
        ModelDb.Card<YxStarMoonFoldingFan>(),
        ModelDb.Card<YxStarryMoon>(),
        ModelDb.Card<YxStarTrailDivination>(),
        ModelDb.Card<YxStillnessCittaDharma>(),
        ModelDb.Card<YxStrikeHeptastarPavilion>(),
        ModelDb.Card<YxStrikeTwice>(),
        ModelDb.Card<YxStrikeVacuity>(),
        ModelDb.Card<YxSunAndMoonForGlory>(),
        ModelDb.Card<YxThinOnTheGround>(),
        ModelDb.Card<YxThrowingStonesForDirections>(),
        ModelDb.Card<YxThrowPetrals>(),
        ModelDb.Card<YxThunderAndLighting>(),
        ModelDb.Card<YxThunderCittaDharma>(),
        ModelDb.Card<YxThunderHexagramRhythm>(),
        ModelDb.Card<YxUltimateHexagramBase>(),
        ModelDb.Card<YxVitalityBlossom>(),
        ModelDb.Card<YxWaitForGainsWithoutPains>(),
        ModelDb.Card<YxWaterDropErosion>(),
        ModelDb.Card<YxWaterHexagram>(),
        ModelDb.Card<YxWhiteCraneBrightWings>(),
        ModelDb.Card<YxWhiteSnake>(),
        ModelDb.Card<YxWildHorsesPartTheMane>(),
        ModelDb.Card<YxWindHexagram>(),
        ModelDb.Card<YxWithinReach>(),
        ModelDb.Card<YxYinYangFormation>(),
        ModelDb.Card<YxZhenHexagram>(),
    ];
}
